site_name: Albert Fougy
site_url: https://albertfougy.com

theme:
  name: terminal
  features:
    - navigation.side.indexes
    - footer.prev_next
    - revision.history


markdown_extensions:
  # Python Markdown
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: '#'
      permalink_title: Anchor link to this section for reference

  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - docs

nav:
    - Home: 'index.md'
    - Cisco CCNA Exam Prep: 
      - Index: 'Cisco-CCNA-Exam-Prep/index.md'
    - Network-Fundamentals: 
      - Index: 'Network-Fundamentals/index.md'
      - Functions Of Networking: 'Network-Fundamentals/exploring-the-functions-of-networking.md'
      - Overview:
        - Index: 'Network-Fundamentals/overview/index.md'
    - About: 
      - Index: 'about/index.md'
      - License: 'about/license.md'
    - Projects:
      - Index: 'projects/index.md'
      - Nerderr: 'projects/nerderr.md'
