site_name: Albert Fougy
site_url: https://albertfougy.com

theme:
  name: terminal
  features:
    - navigation.side.indexes
    - footer.prev_next
    - revision.history

plugins:
  - exclude:
      glob:
        - exclude/this/path/*
        - '*.tmp'
        - '*.pdf'
        - '*.gz'
        - '.DS_Store'
      regex:
        - '.*\.(tmp|bin|tar)$'



markdown_extensions:
  # Python Markdown
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: '#'
      permalink_title: Anchor link to this section for reference

  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - docs

nav:
    - Home: 'index.md'
    - Cisco CCNA Exam Prep: 'Cisco-CCNA-Exam-Prep.md'
    - Network-Fundamentals: 
      - Index: 'Network-Fundamentals/index.md'
      - Functions Of Networking: 'Network-Fundamentals/exploring-the-functions-of-networking.md'
      - Network Definition: 'Network-Fundamentals/what-is-a-computer-network.md'
      - Release Notes:
        - Index: 'Network-Fundamentals/release-notes/index.md'
    - About: 
      - Index: 'about/index.md'
      - License: 'about/license.md'
